# -*- coding: utf-8 -*-
"""Rulebased_chatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h3snxAzt_yvZBQE6yhhcWQVo8Sbpmcc8
"""

import re
import random



class Rulebot:
  negative_responses = ("no","nope","not a chance")
  exit_commands = ("quit","exit")
  random_question = (
       "why are you here?",
       "are there many humans like u?"
   )
  
  def __init__(self):
   self.alienbabble = {'describe_planet_intent': r'.*\s*your planet.*',
                        'answer_why_intent': r'why\sare.*',
                        'about_intenllipat': r'.*\s*intellipaat'
                        }

  def greet(self):
   self.name = input("what is your name?\n")
   will_help = input(
       f"hi {self.name}, i am Rule based naku bot \n")
   if will_help in self.negative_responses:
      print("ok, have a nice Earth day da venna!")
      return
      self.chat()


   def make_exit(self, reply):
    for command in self.exit_commands:
     if reply  == command:
       print("okay have nice earth day da venna")
       return True

   def chat(self):
    reply = input(random.choice(self.random_question)).lower()
    while not self.make_exit(reply):
        reply = input(self.match_reply(reply))


   def match_reply(self, reply):
    for key, value in self.alienbabble.items():
      intent = key
      regex_pattern = value
      found_match = re.match(regex_pattern, reply)
    if found_match and intent == 'describe_planet_intent':
        return self.describe_planet_intent()
    elif found_match and intent == 'answer_why_intent':
        return self.answer_why_intent()
    elif found_match and intent == 'about_intenllipat':
        return self.about_intenllipat()
    if not found_match:
       return self.no_match_intent()

   def describe_planet_intent(self):
     responses = ("My planet is a utopia of diverse organisms and species.\n",
               "I am from Opidipus, the capital of the wayward galaxies.\n")
     return random.choice(responses)


   def answer_why_intent(self):
     responses = ("i come in peace\n","I heard the coffee is good\n")
     return random.choice(responses)


   def about_intenllipat(self):
      responses = ("intellipat is a word but idont know da.\n",
               "you again speak intent da punda i donknow da.\n")
      return random.choice(responses)


   def no_match_intent(self):
       responses = ("please tell me more.\n",
               "tell me more da punda \n",
               "can you tell me more \n")
       return random.choice(responses)


Alienbot = Rulebot()
Alienbot.greet()