# -*- coding: utf-8 -*-
"""Web_DATA_FETCHING_BOT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13y428f2hu6BqO1eTyo-drPxuP8LrM2I2
"""

pip install nltk

pip install newspaper3k

#library files acces part
from newspaper import Article
import random 
import string
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import warnings
warnings.filterwarnings('ignore')

nltk.download('punkt',quiet=True)

# Article fetching part
article = Article('https://www.javatpoint.com/corejava-interview-questions')
article.download()
article.parse()
article.nlp()
jp = article.text

print(jp)

#token part
text = jp
sentence_list = nltk.sent_tokenize(text)

print(sentence_list)

# function for responce
def greeting_response(text):
   text = text.lower()
   
   #bots response
   bot_greetins = ['hii','hello','vanakam','heyy']
   #user response
   user_greetings = ['hii','hello','vanakam']

   for word in text.split():
      if word in user_greetings:
        return random.choice(bot_greetins)

def index_sort(list_var):
  length = len(list_var)
  list_index = list(range(0, length))
  x = list_var
  for i in range(length):
   for j in range(length):
     if x[list_index[i]] > x[list_index[j]]:
       # swap 
       temp = list_index[i]
       list_index[i] = list_index[j]
       list_index[j] = temp
  
  return list_index

from requests import Response
#bot responce
def bot_response(user_input): 
 user_input = user_input.lower()
 sentence_list.append(user_input)
 bot_response = ''
 cm = CountVectorizer().fit_transform(sentence_list)
 similarity_scores = cosine_similarity(cm[-1], cm)
 similarit_scores_list = similarity_scores.flatten()
 index = index_sort(similarit_scores_list)
 index = index[1:]
 response_flag = 0

 jk = 0
 for i in range(len(index)):
   if similarit_scores_list[index[i]] > 0.0:
     bot_response = bot_response+''+sentence_list[index[i]]
     response_flag = 1
     jk = jk+1
   if jk < 2:
     break
  #note panniko daaa

 if response_flag == 0:
  bot_response = bot_response+''+'i apologize,I want check my developer for your information...'

  sentence_list.remove(user_input)

  return bot_response

# start the chat
print ('Teaching Bot: I am Your Trainer for Your Technical Interview Rounds Ask some coding Questions...')

exit_list = ['exit','see you later','bye','quit','exit']

while(True):
  user_input = input()

  if user_input.lower() in exit_list:
    print('Teaching Bot: Thirumbi vantha mandaya odipaaa...')
    break
  else:
    if greeting_response(user_input)!= None:
     print('Teaching Bot: '+greeting_response(user_input))
    else:
      print('nakku bot: '+bot_response(user_input))